mysite/shopapp/urls.py
from django.urls import path
from . import views

app_name = "shopapp"
urlpatterns = [
    path("", views.ShopIndexView.as_view(), name="index"),
    path("groups/", views.GroupsListView.as_view(), name="groups_list"),
    path("products/", views.ProductsListView.as_view(), name="products_list"),
    path("products/export/", views.ProductExportView.as_view(), name="products-export"),
    path("products/<int:pk>/", views.ProductDetailsView.as_view(), name="products_details"),
    path("products/create/", views.ProductCreateView.as_view(), name="product_create"),
    path("products/<int:pk>/update/", views.ProductUpdateView.as_view(), name="product_update"),
    path("products/<int:pk>/archive/", views.ProductDeleteView.as_view(), name="product_delete"),

    path("orders/", views.OrderListView.as_view(), name="orders_list"),
    path("orders/export/", views.OrdersDataExportView.as_view(), name="orders_export"),
    path("orders/<int:pk>/", views.OrderDetailsView.as_view(), name="order_details"),
    path("orders/create/", views.OrderCreateView.as_view(), name="order_create"),
    path("orders/<int:pk>/update/", views.OrderUpdateView.as_view(), name="order_update"),
    path("orders/<int:pk>/archive/", views.OrderDeleteView.as_view(), name="order_delete"),

    path("about/", views.shop_about, name="about"),
    path("contact/", views.shop_contact, name="contact"),
]

mysite/shopapp/models.py
from django.contrib.auth.models import User
from django.db import models


def product_preview_directory_path(instance: "Product", filename: str) -> str:
    return "products/product_{pk}/preview/{filename}".format(
        pk=instance.pk,
        filename=filename
    )


class Product(models.Model):
    class Meta:
        ordering = ["name", "price"]

    name = models.CharField(max_length=100)
    description = models.TextField(null=False, blank=True)
    price = models.DecimalField(default=0, max_digits=8, decimal_places=2)
    diccount = models.SmallIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    archived = models.BooleanField(default=False)
    created_by = models.ForeignKey(User, on_delete=models.PROTECT, default=2)
    preview = models.ImageField(null=True, blank=True, upload_to=product_preview_directory_path)

    def __str__(self) -> str:
        return f"Product(pk={self.pk}, name={self.name!r}"


def product_images_directory_path(instance: "ProductImage", filename: str) -> str:
    return "products/product_{pk}/images/{filename}".format(
        pk=instance.product.pk,
        filename=filename
    )


class ProductImage(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name="images")
    image = models.ImageField(upload_to=product_images_directory_path)
    description = models.CharField(max_length=200, null=False, blank=True)


class Order(models.Model):
    delivery_address = models.CharField(max_length=50, null=True, blank=True)
    promocode = models.CharField(max_length=20, null=False, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.PROTECT)
    products = models.ManyToManyField(Product, related_name="orders")
    archived = models.BooleanField(default=False)
    receipt = models.FileField(null=True, upload_to='orders/receipts/')

mysite/shopapp/templates/shopapp/about.html
{% extends "shopapp/base.html" %}

{% block title %}shop about{% endblock %}

{% block body %}

<h1>О нашей компании </h1>
<div>
    <p>
        {% if text|length > 312 %}
        Текст слишком длинный ({{ text|length }} символов ). Используйте не более 312 знаков
        {% else %}
            {{ text }}
        {% endif %}
    </p>

</div>

{% endblock %}

mysite/shopapp/templates/shopapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
      {% block title %}
      Base Title
      {% endblock %}
    </title>
</head>
<body>
      {% block body %}
      Base body
      {% endblock %}

<div>
    <br>
    Текущее время {% now 'H:i' %}
</div>
<div>
    {% include "shopapp/media.html" %}
</div>

</body>
</html>

mysite/shopapp/templates/shopapp/contacts.html
{% extends "shopapp/base.html" %}

{% block title %}contact{% endblock %}

{% block body %}
<h1>Контакты нашей компании</h1>
        <p>Телефон: 8(800)2000-600</p>
        <p>Email: 111@mail.ru</p>
        <p>Адреса офисов</p>
        <p>Всего {{ addresses | length }} aдреса</p>
    <ul>
        {% for address in addresses %}
        <li> {{ address }} </li>
        {% empty %}
            Пока не открыто ни одного мазагина
        {% endfor %}

    </ul>


{% endblock %}

mysite/shopapp/templates/shopapp/create-product.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Create product
{% endblock %}

{% block body %}
    <h1>Create a new product</h1>
    <div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Create</button>
        </form>
    </div>
<div>
    <a href="{% url 'shopapp:products_list' %}">Back to Products list</a>
</div>
{% endblock %}

mysite/shopapp/templates/shopapp/groups_list.html
{% extends "shopapp/base.html" %}

{% block title %}
    Groups List
{% endblock %}

{% block body %}
    <h1>Groups:</h1>
    <div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Create</button>
        </form>
    </div>
    <div>
        {% if not groups %}
            <h3>
                Пока нет групп
            </h3>
        {% else %}
            <ul>
                {% for group in groups %}
                    <li>
                        <div>{{ group.name }}</div>
                        <ul>
                            {% for permission in group.permissions.all %}
                                <li>
                                    {{ permission.name }}
                                    (<code> {{ permission.codename }} </code>)
                                </li>
                            {% endfor %}
                        </ul>
                    </li>
                {% endfor %}
            </ul>
        {% endif %}
    </div>
{% endblock %}

mysite/shopapp/templates/shopapp/media.html
<p>Наши социальные сети: Twitter, VC, FB, IG</p>

mysite/shopapp/templates/shopapp/order_confirm_delete.html
{% extends "shopapp/base.html" %}

{% block title %}
    Deletion of order #{{ object.pk }}
{% endblock %}

{% block body %}
    <h1>Are you sure you want to delete order #{{ object.pk }}?</h1>
    <br>
    <div>
        <a href="{% url 'shopapp:order_details' pk=object.pk %}">Back to order</a>
    </div>
    <br>
    <div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Delete</button>
        </form>
    </div>
{% endblock %}

mysite/shopapp/templates/shopapp/order_list.html
{% extends "shopapp/base.html" %}

{% block title %}
    Orders List
{% endblock %}

{% block body %}
    <h1>Orders:</h1>
    {% if object_list %}
        <div>
            {% for order in object_list %}
            <div>
                <p><a href="{% url 'shopapp:order_details' pk=order.pk %}">Details #{{ order.pk }}</a></p>
                <p><b>Order by:</b> {% firstof order.user.first_name order.user.username %}</p>
                <p><b>PromoCode:</b> <code>{{ order.promocode }}</code></p>
                <p><b>Delivery address:</b> {{ order.delivery_address }}</p>
                <div>
                    <b>Product in order</b>
                <lu>
                    {% for product in order.products.all %}
                    <li>{{ product.name }} for ${{ product.price }}</li>
                    {% endfor %}
                </lu>
                </div>
            </div>
            _______________________________
            <br>
            {% endfor %}
        </div>
    {% else %}
        <h3>No orders yet</h3>
    {% endif %}
    <br>
    <div>
        <a href="{% url 'shopapp:order_create' %}">Create a new Order </a>
    </div>
{% endblock %}

mysite/shopapp/templates/shopapp/order_update_form.html
{% extends "shopapp/base.html" %}

{% block title %}
    Update Order
{% endblock %}

{% block body %}
    <h1>Update Order</h1>
    <div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Update</button>
        </form>
    </div>
    <div>
        <a href="{% url 'shopapp:order_details' pk=object.pk %}">Back to order #{{ object.pk }}</a>
    </div>
{% endblock %}

mysite/shopapp/templates/shopapp/product-details.html
{% extends "shopapp/base.html" %}

{% block title %}
    Product # {{ product.pk }}
{% endblock %}

{% block body %}
    <h1>Product <strong>{{ product.name }}</strong></h1>
    <div>
        <div>Description: <em>{{ product.description }}</em> </div>
        <div>Price: {{ product.price }}</div>
        <div>Discount: {{ product.diccount }}</div>
        <div>Archived: {{ product.archived }}</div>

        {% if product.preview %}
            <img src="{{ product.preview.url }}" alt="{{ product.preview.name }}">
        {% endif %}

        <h3>Images:</h3>
        <div>
            {% for img in product.images.all %}
                <div>
                    <img src="{{ img.image.url }}" alt="{{ img.image.name }}">
                    <div>{{ img.description }}</div>
                </div>
            {% empty %}
                <div>No images uploaded yet</div>
            {% endfor %}
        </div>
    </div>
    <div>
        {% if perms.shopapp.change_product or product.created_by_id == user.pk or product.user.is_superuser %}
            <a href="{% url 'shopapp:product_update' pk=product.pk %}">Update Product</a>
        {% endif %}
    </div>
    <div>
        <a href="{% url 'shopapp:product_delete' pk=product.pk %}">Archive Product</a>
    </div>
    <div>
        <a href="{% url 'shopapp:products_list' %}">Back to products list</a>
    </div>
{% endblock %}

mysite/shopapp/templates/shopapp/product_confirm_delete.html
{% extends "shopapp/base.html" %}

{% block title %}
    Confirm archive {{ object.name }}
{% endblock %}

{% block body %}
    <h1>Are you sure you want to archive {{ object.name }}?</h1>
    <br>
    <div>
        <a href="{% url 'shopapp:products_details' pk=object.pk %}">Back to product</a>
    </div>
    <br>
    <div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Archived</button>
        </form>
    </div>
{% endblock %}

mysite/shopapp/templates/shopapp/product_form.html
{% extends "shopapp/base.html" %}

{% block title %}
    Create Product
{% endblock %}

{% block body %}
    <h1>Create a new Product</h1>
    <div>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Create</button>
        </form>
    </div>
    <div>
        <a href="{% url 'shopapp:products_list' %}">Back to products list</a>
    </div>
{% endblock %}

mysite/shopapp/templates/shopapp/products-list.html
{% extends "shopapp/base.html"  %}

{% block title %}
    Products list
{% endblock %}

{% block body %}
    <h1> Products: </h1>
    {% if products %}
        <div>
            {% for product in products %}
            <div>
                <p><a href="{% url 'shopapp:products_details' pk=product.pk %}">Name: {{ product.name }}</a></p>
                <p>Price: {{ product.price }}</p>
                <p>Discount: {% firstof product.diccount "no discount" %}</p>

                {% if product.preview %}
                    <img src="{{ product.preview.url }}" alt="{{ product.preview.name }}">
                {% endif %}
            </div>
            {% endfor %}
        </div>
    {% else %}
    <h3>No Products</h3>
    {% endif  %}

    <div>
        {% if perms.shopapp.add_product %}
            <a href="{% url 'shopapp:product_create' %}">Create a new Product</a>
        {% endif %}
    </div>
{% endblock %}

mysite/shopapp/templates/shopapp/shop-index.html
{% extends "shopapp/base.html" %}


{% block title %}shop index{% endblock %}

{% block body %}

<h1>Список нашей техники</h1>
<div>
    <ul>
        {% for name, price in products %}
        <li>{{ name }} for {{ price }} </li>
        {% if name|length_is:"7" %}
        <span>Lucky product:</span>
        {% endif %}
        {% empty %}
            No products here
        {% endfor %}
    </ul>
</div>
<div>
    Time running {{ time_running }}
</div>

{% endblock %}