mysite/myauth/urls.py
from django.contrib.auth.views import LoginView
from django.urls import path


from . import views

app_name = "myauth"
urlpatterns = [
    # path("login/", views.login_view, name="login"),
    path(
        "login/",
        LoginView.as_view(
            template_name='myauth/login.html',
            redirect_authenticated_user=True,
        ),
        name="login"),

    path("about-me/", views.AboutMeView.as_view(), name="about-me"),
    path("register/", views.RegisterView.as_view(), name="register"),
    path("about-me/<int:pk>/update/", views.ProfileUpdateView.as_view(), name="profile_update"),
    path("profiles/", views.ProfileListView.as_view(), name="profiles_list"),
    path("about-profile/<int:pk>/", views.AboutProfileView.as_view(), name="about-profile"),

    # path("logout/", views.logout_view, name="logout"),
    path("logout/", views.MyLogoutView.as_view(), name="logout"),

    path("cookie/set/", views.set_cookie_view, name="cookie-set"),
    path("cookie/get/", views.get_cookie_view, name="cookie-get"),

    path("session/set/", views.set_session_view, name="session-set"),
    path("session/get/", views.get_session_view, name="session-get"),

    path("foo-bar", views.FooBarView.as_view(), name="foo-bar"),
]

mysite/myauth/models.py
from django.contrib.auth.models import User
from django.db import models


def profile_avatar_directory_path(instance: "Profile", filename: str) -> str:
    return "Profiles/profile_{pk}/avatar/{filename}".format(
        pk=instance.pk,
        filename=filename
    )


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(max_length=500, blank=True)
    agreement_accepted = models.BooleanField(default=False)
    avatar = models.ImageField(null=True, blank=True, upload_to=profile_avatar_directory_path)

mysite/myauth/views.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.models import User
from django.contrib.auth.views import LogoutView
from django.http import HttpRequest, HttpResponse, JsonResponse
from django.shortcuts import render, redirect, reverse
from django.contrib.auth import authenticate, login, logout
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import TemplateView, CreateView, UpdateView, ListView, DetailView

from django.contrib.auth.decorators import login_required, permission_required, user_passes_test

from .models import Profile



class ProfileListView(ListView):
    template_name = "myauth/profile-list.html"
    model = User
    context_object_name = 'profiles'
    def get_queryset(self):
        return User.objects.all()




class AboutMeView(DetailView):
    template_name = "myauth/about-me.html"
    model = User
    # queryset = User.objects.prefetch_related("bio")
    # context_object_name = "user"

class AboutProfileView(DetailView):
    template_name = "myauth/about-profile.html"
    model = User
    context_object_name = "profile"


class RegisterView(CreateView):
    form_class = UserCreationForm
    template_name = "myauth/register.html"
    success_url = reverse_lazy("myauth:about-me")

    def form_valid(self, form):
        resource = super().form_valid(form)
        Profile.objects.create(user=self.object)
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password1")
        user = authenticate(self.request, username=username, password=password)
        login(request=self.request, user=user)
        return resource


class ProfileUpdateView(UpdateView):
    model = User
    template_name_suffix = "_update_form"
    fields = "user", "bio", "avatar"
    success_url = reverse_lazy("myauth:about-me")



def login_view(request: HttpRequest):
    if request.method == "GET":
        if request.user.is_authenticated:
            return redirect('/admin/')

        return render(request, 'myauth/login.html')

    username = request.POST["username"]
    password = request.POST["password"]
    user = authenticate(request, username=username, password=password)
    if user:
        login(request, user)
        return redirect('/admin/')

    return render(request, 'myauth/login.html', {"error": "Invalid login credentials"})

def logout_view(request: HttpRequest) -> HttpResponse:
    logout(request)
    return redirect(reverse("myauth:login"))

class MyLogoutView(LogoutView):
    next_page = reverse_lazy("myauth:login")











@user_passes_test(lambda u: u.is_superuser)
def set_cookie_view(request: HttpRequest) -> HttpResponse:
    response = HttpResponse("Cookie set")
    response.set_cookie("fizz", "buzz", max_age=3600)
    return response

def get_cookie_view(request: HttpRequest) -> HttpResponse:
    value = request.COOKIES.get('fizz', 'default value')
    return HttpResponse(f"Cookie value: {value!r}")


@permission_required("myauth.view_profile", raise_exception=True)
def set_session_view(request: HttpRequest) -> HttpResponse:
    request.session["foobar"] = "spameggs"
    return HttpResponse("Session set!")


@login_required
def get_session_view(request: HttpRequest) -> HttpResponse:
    value = request.session.get("foobar", "default")
    return HttpResponse(f"Session value: {value!r}")

class FooBarView(View):
    def get(self, request: HttpRequest) -> JsonResponse:
        return JsonResponse({"foo": "bar", "spam": "eggs"})

mysite/myauth/templates/myauth/about-me.html
{% extends 'myauth/base.html' %}

{% block title %}
    About Me
{% endblock %}

{% block body %}
    <h1>User Info</h1>
    {% if user.is_authenticated %}
        <h2>Detail:</h2>
        {% if user.profile.avatar %}
            <img src="{{ user.profile.avatar.url }}" alt="{{ user.profile.avatar.name }}" style="width: 100px;">
        {% else %}
            <div>No images uploaded yet</div>
        {% endif %}

        <p>User: {{ user.username }}</p>
        <p>First name: {{ user.first_name }}</p>
        <p>Last name: {{ user.last_name }}</p>
        <p>Email: {{ user.email }}</p>
        <p>Bio: {{ user.profile.bio }}</p>
    {% else %}
        <h2>User is anonymous</h2>
    {% endif %}

  <div>
      <a href="{% url 'myauth:profile_update' pk=user.pk %}">Update Profile</a>
  </div>
{% endblock %}

mysite/myauth/templates/myauth/about-profile.html
{% extends 'myauth/base.html' %}

{% block title %}
    About Me
{% endblock %}

{% block body %}
    <h1>User Info</h1>
    {% if user.is_authenticated %}
        <h2>Detail:</h2>
        {% if profile.profile.avatar %}
            <img src="{{ profile.profile.avatar.url }}" alt="{{ profile.profile.avatar.name }}" style="width: 100px;">
        {% else %}
            <div>No images uploaded yet</div>
        {% endif %}

        <p>User: {{ profile.username }}</p>
        <p>First name: {{ profile.first_name }}</p>
        <p>Last name: {{ profile.last_name }}</p>
        <p>Email: {{ profile.email }}</p>
        <p>Bio: {{ profile.profile.bio }}</p>

    {% else %}
        <h2>User is anonymous</h2>
    {% endif %}

  <div>
        {% if profile.profile.user.pk == user.id %}
            <a href="{% url 'myauth:profile_update' pk=user.pk %}">Update Profile</a>
        {% endif %}
    </div>
{% endblock %}

mysite/myauth/templates/myauth/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
        {% endblock %}
    </title>
</head>
<body>
    {% block body %}
    {% endblock %}
</body>
</html>

mysite/myauth/templates/myauth/login.html
{% extends 'myauth/base.html' %}

{% block title %}
login
{% endblock %}

{% block body %}
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Login</button>
</form>
{% endblock %}

mysite/myauth/templates/myauth/profile-list.html
{% extends "myauth/base.html"  %}

{% block title %}
    Profiles list
{% endblock %}

{% block body %}
    <h1> Profiles: </h1>
    {% if profiles %}
        <div>
            {% for profile in profiles %}
            <div>
                <p><a href="{% url 'myauth:about-profile' pk=profile.pk %}">Name: {{ profile.username }}</a></p>
                <p>User: {{ profile.username }}</p>
                <p>First name: {{ profile.first_name }}</p>
                <p>Last name: {{ profile.last_name }}</p>
            </div>
            {% endfor %}
        </div>
    {% else %}
    <h3>No Profiles</h3>
    {% endif  %}
{% endblock %}

mysite/myauth/templates/myauth/profile_update_form.html
{% extends "myauth/base.html" %}

{% block title %}
    Update Profile
{% endblock %}

{% block body %}
    <h1>Update Profile</h1>
    <div>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Update</button>
        </form>
    </div>

{% endblock %}

mysite/myauth/templates/myauth/register.html
{% extends 'myauth/base.html' %}

{% block title %}
    Register
{% endblock %}

{% block body %}
    <h1>Register</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Register">
    </form>
{% endblock %}